### ISSUE TITLE
Files not visible

### ISSUE THREAD

**Issue by ronylee11** [Laikaiyong/React-Native-Learning#1]
Hi, i can't see the files
Please upload them asap so i can learn from u <3

**Comment by Laikaiyong** [comment]
I will upload the files as soon as possible 
![bitmoji](https://sdk.bitmoji.com/render/panel/5cdb5977-b8b9-4261-9f98-deef7c1bedee-aa2c072a-4181-413c-8e8e-05c4920d77ad-v1.png?transparent=1&palette=1&width=246)
